version: '3.7'

services:
  app:
    container_name: app
    build: .
    entrypoint: sh -c "npm install && npm run dev"
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=